### PR TITLE
add enhanched OMPython functionality

### PR DESCRIPTION
**Pull request by arun3688**

### CODE REVIEW

**Comment by lochel** [comment]
@arun3688 What does "enhanced functionality" mean?

**Comment by arun3688** [comment]
There are some new API functionality added, this was a part of thesis work from student sudeep, more information can be read in this file 
[UsersGuide_OMPythonAPI.pdf](https://github.com/OpenModelica/OMPython/files/748741/UsersGuide_OMPythonAPI.pdf)

**Comment by bilderbuchi** [comment]
@arun3688 @adeas31 does this PR supersede the PRs #7 and #8? If so, these should be closed. 
Btw, thank you for adding some docstrings, and apparently fixed at least some of the things noted in #7 and #8. :-) 👍

**Comment by bilderbuchi** [comment]
btw, the new numpy dependency is not mentioned in setup.py [installed_requires](https://github.com/OpenModelica/OMPython/blob/57a534a04f53e4009aa0a75b8030f2e78b21b006/setup.py#L52).

**Comment by adeas31** [comment]
@bilderbuchi I guess PR #7 and #8  are not required now. @arun3688 can you check and close them.
I have already asked @arun3688 to mention numpy dependency in setup.py

**Comment by thorade** [comment]
Consider using find_packages for the setup.py file:
http://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages

**Pull request merged**
