### PR TITLE
Added ZeroMQ client for OMC

### PR DESCRIPTION
**Pull request by adeas31**
Implemented a new class OMCSessionZMQ. OMCSession still exits. Both OMCSession and OMCSessionZMQ inherits from OMCSessionBase.
ModelicaSystem class has a new parameter useCorba which is False by default. So ModelicaSystem by default always use OMCSessionZMQ. If you want to use OMCSession then set `useCorba=True`.

### CODE REVIEW

**Comment by hkiel** [comment]
@adeas31 Are you going to implement ZMQ for OMNotebook as well?

**Comment by adeas31** [comment]
@hkiel why do you need ZMQ for OMNotebook?
OMNotebook directly loads the OpenModelicaCompiler binary and communicate via the C interface.

**Comment by thorade** [comment]
Maybe he wanted to ask about the Jupyter kernel, not OMNotebook?
https://github.com/OpenModelica/jupyter-openmodelica

**Comment by adeas31** [comment]
Well openmodelica jupyter kernal uses OMPython.
However, it is using `OMCSession` perhaps we can update it to use `OMCSessionZMQ`.

**Comment by bilderbuchi** [comment]
Great to see this! :+1:

**Comment by dietmarw** [comment]
So does the jupyter kernel now already use OMCSessionZMQ?

**Comment by dietmarw** [comment]
Also it looks like the documentation was forgotten as to what packages OMPython now needs to run. Could this be updated?

**Comment by arun3688** [comment]
No the jupyter kernel is not using ZMQ, i will change it by next week

regards
arun

**Comment by thorade** [comment]
I just tried to install it (on Travis), but installation fails with error message 
`FileNotFoundError: [Errno 2] No such file or directory: 'omniidl'`
Is that still required? There are no pypi packages for omniidl.

**Comment by hkiel** [comment]
I was referring to OMMNotebook and OMShell as these currently use corba for communication to omc

**Comment by adeas31** [comment]
OMNotebook does not use CORBA. I updated it to directly link the OpenModelica binary long ago.
OMShell still uses CORBA and is fine with it.

**Comment by adeas31** [comment]
@dietmarw I updated the version number.
@thorade It should be fixed in #24. Try again. Note that you also need the latest omc with ZeroMQ so that `omc -d=interactiveZMQ` is possible.

**Comment by adeas31** [comment]
> I dislike you naming the flag -d=interactiveZMQ though... Should have been changed to --interactive=none|tcp|zmq|corba or something while we were fixing things :)

Not really. That change wouldn't be backward compatible. We do have a lot of people using CORBA interface via `-d=interactiveCorba`.

**Comment by dietmarw** [comment]
Why not implement it in the proposed cleaner way like @sjoelund suggested and leave the alias `-d=interactiveCorba` -> `--interactive=corba` with a deprecation warning for backward compatibility?

**Comment by pierre-haessig** [comment]
I've seen the README updated to mention PyZMQ as a dependency. What is not clear to me is whether now omniORB is still a *hard dependency* or if it is *optional*.

As a related question, is OMPython still compatible with Python <=2.7 only ?

**Comment by dietmarw** [comment]
The whole README is currently not usable when it comes to installation. The path given don't exist on linux since OMPython is not packaged with the Linux version. There is still the unnecessary git dependency in the instructions.

So the README should have clean instructions for Windows and Linux separate which are tested. Otherwise new users will just be frightened away from OMPython ;-)

**Comment by thorade** [comment]
@pierre-haessig Python 3 compatibility is also discussed in #1.

**Comment by adeas31** [comment]
>> I dislike you naming the flag -d=interactiveZMQ though... Should have been changed to --interactive=none|tcp|zmq|corba or something while we were fixing things :)

> Not really. That change wouldn't be backward compatible. We do have a lot of people using CORBA interface via -d=interactiveCorba.

@sjoelund @dietmarw See https://github.com/OpenModelica/OMCompiler/pull/1687

**Comment by pierre-haessig** [comment]
As a side question, is ZMQ available from within a Modelica simulation or is it specific to OMC ?

**Comment by adeas31** [comment]
> As a side question, is ZMQ available from within a Modelica simulation or is it specific to OMC ?

It is specific to OMC.

**Comment by arun3688** [comment]
@dietmarw , The Jupyter kernel for OpenModelica is now changed to use OMCSessionZMQ

**Comment by dietmarw** [comment]
@arun3688 Great. With "now" you mean today so it will be in the next nightly?

**Comment by arun3688** [comment]
@dietmarw , the jupyter kernel is not part of Nightly builds, but OMPython comes under nightly builds, But anyhow the jupyter openmodelica kernel should run in python 3 as well as

**Comment by dietmarw** [comment]
OK, I wasn't sure if the kernel changes would also need some omc code changes.

**Pull request merged**
