### PR TITLE
Remove distutils, update CI

### PR DESCRIPTION
**Pull request by AnHeuermann**
### Related Issues

Fixes https://github.com/OpenModelica/OMPython/issues/175, fixes https://github.com/OpenModelica/OMPython/issues/164.

### Changes

  - Replace distutils with setuptools and shutil
  - Update README.md
  - Update CI to test Python 3.10 and 3.12
  - Adding dependabot for GitHub actions
  - Update OMPython version to 3.6.0

### CODE REVIEW

**Review by arun3688 — APPROVED** [review]

**Comment by AnHeuermann** [comment]
@arun3688 how do we upload new releases for pip? Can you do that?

**Comment by arun3688** [comment]
@AnHeuermann sure i will upload new pip package

**Comment by arun3688** [comment]
@AnHeuermann uploaded the new pip package `https://pypi.org/project/OMPython/`

**Comment by syntron** [comment]
I just updated OMPython and checked on this page for details about 3.6.0 - this page is missing the release data while it is available via pip!

**Comment by casella** [comment]
@syntron which page?

**Comment by syntron** [comment]
The release page at github - see https://github.com/OpenModelica/OMPython/releases

**Comment by casella** [comment]
@arun3688 could you please fix that? Thanks!

**Pull request merged**
