### PR TITLE
use pip also for local install

### PR DESCRIPTION
**Pull request by thorade**
plus, use `--upgrade` in case an older OMPython was already installed
this is for #21 and #26
https://stackoverflow.com/q/2087148/874701

### CODE REVIEW

**Comment by adeas31** [comment]
This doesn't work on Windows,

```
C:\OpenModelica\build\share\omc\scripts\PythonInterface>python -m pip install --upgrade .
Processing c:\openmodelica\build\share\omc\scripts\pythoninterface
Collecting pyparsing (from OMPython==3.0.0)
  Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
    100% |################################| 61kB 85kB/s
Collecting numpy (from OMPython==3.0.0)
  Downloading numpy-1.13.0-cp27-none-win_amd64.whl (7.6MB)
    100% |################################| 7.6MB 130kB/s
Requirement already up-to-date: pyzmq in c:\python27\lib\site-packages (from OMPython==3.0.0)
Installing collected packages: pyparsing, numpy, OMPython
  Found existing installation: pyparsing 2.1.10
    Uninstalling pyparsing-2.1.10:
      Successfully uninstalled pyparsing-2.1.10
  Rolling back uninstall of pyparsing
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Python27\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Python27\lib\site-packages\pip\wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "C:\Python27\lib\site-packages\pip\locations.py", line 140, in distutils_scheme
    d = Distribution(dist_args)
  File "C:\Python27\lib\site-packages\setuptools\dist.py", line 316, in __init__
    for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 730, in iter_entry_points
    entries = dist.get_entry_map(group)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2639, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2369, in parse_map
    for group, lines in data:
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2967, in split_sections
    for line in yield_lines(s):
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2235, in yield_lines
    for ss in strs:
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 2564, in _get_metadata
    if self.has_metadata(name):
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1462, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1822, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1702, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\Python27\lib\site-packages\pkg_resources\__init__.py", line 1642, in load
    mtime = os.stat(path).st_mtime
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Python27\\lib\\site-packages\\pyparsing-2.1.10-py2.7.egg'
```

**Comment by thorade** [comment]
Is this due to the pyparsing version?

**Comment by thorade** [comment]
Oh, I see you get an error even during installation. That did not happen on my machine, tested it in three different WinPython versions...

**Comment by adeas31** [comment]
Its probably becasue of pyparsing is installed in a different way when `python setup.py install` is used.
However, your latest changes does work fine so I am merging this PR.

**Pull request merged**
