### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by sjoelund**
For example, use `OMCSessionZMQ(docker="openmodelica/openmodelica:v1.16.0-minimal")`

### CODE REVIEW

**Comment by adeas31** [comment]
Gives this error on Windows,

```
def _create_omc_log_file(self, suffix):
        if sys.platform == 'win32':
            self._omc_log_file = open(os.path.join(self._temp_dir, "openmodelica.{0}.{1}.log".format(suffix, self._random_string)), 'w')
        else:
            try:
              self._currentUser = getpass.getuser()
              if not self._currentUser:
                  self._currentUser = "nobody"
            except KeyError:
              # We are running as a uid not existing in the password database... Pretend we are nobody
              self._currentUser = "nobody"
            # this file must be closed in the destructor
            self._omc_log_file = open(os.path.join(self._temp_dir, "openmodelica.{0}.{1}.{2}.log".format(self._currentUser, suffix, self._random_string)), 'w')
```

**Review by adeas31 — DISMISSED** [review]
Add `psutil` to `setup.py`

**Comment by adeas31** [comment]
Maybe add an example with port use.

**Comment by sjoelund** [comment]
I thought to add that to the OM documentation. There are no example commands in this repository, right? I looked for it and didn't find any...

**Comment by sjoelund** [comment]
Or do you mean testcases? I'm a little hesitant since it might randomly fail...

**Comment by adeas31** [comment]
I mean to add a testcase for it.

As that is the only way in Windows so it has to be clearly mentioned in users guide. I also suggest to write it in the README.

**Review by adeas31 — APPROVED** [review]

**Comment by sjoelund** [comment]
The README only has `help(OMPython)` :D

**Pull request merged**
