### PR TITLE
Changed to use list instead of string for subprocess command.

### PR DESCRIPTION
**Pull request by j-emils**
### Related Issues

[](https://github.com/OpenModelica/OMPython/issues/206)

### Purpose

Cannot execute the simulate method on linux.

### Approach

Adapting subprocess input.

### CODE REVIEW

**Comment by arun3688** [comment]
@j-emils Thanks for the fix

**Comment by arun3688** [comment]
@j-emils Thanks for the fix

**Comment by lafrech** [comment]
I came to report this until I realized it was fixed in master branch already. Thanks @j-emils for the fix.

A proper resolution would be to create the list in the first place rather than concatenate strings then split, but oh well.

Also, I believe the list should be split one step further to separate e.g. `-r` and the file path.

See for instance [Popen docs](https://docs.python.org/3/library/subprocess.html#subprocess.Popen):

```py
    Popen(["/usr/bin/git", "commit", "-m", "Fixes a bug."])
```

although I can't comment on the consequences of not doing it.

I did it like this as a test but really, it would be more sensible to build the list in the first place.

```py
cmd = sum([r.split("=") for r in cmd.split()], [])
```

@arun3688 considering the fixes that have been merged since last release, a new release would be greatly appreciated.

Thanks!

**Comment by casella** [comment]
@j-emils do you mean you'd like to get this fix in OpenModlica 1.23.x?

**Comment by arun3688** [comment]
@j-emils A new release has been made with v.3.5.2 and also the pip package has been updated with the new release `pip install OMPython==3.5.2`

**Comment by j-emils** [comment]
@lafrech, I agree that a more thorough solution would be to create the list from the get go. However, the focus of this fix was to resolve the immediate issue of the code not working. In the future there is a need for refactoring the code in my opinion.

**Comment by lafrech** [comment]
@j-emils I totally understand and agree
@casella done: #217

Have a nice day, guys.

**Pull request merged**
