### PR TITLE
Don't try to generate OMPythonIDL file omniidl is not available.

### PR DESCRIPTION
**Pull request by adeas31**
Updated installation notes in README.md

### CODE REVIEW

**Comment by thorade** [comment]
Thanks, now the first step seems to work, but I now get another error:
`error: package directory 'OMPythonIDL' does not exist`
setup.py is stating, what packages are provided, probably that is the reason

**Comment by adeas31** [comment]
Yeah of course we need to check what packages need to be installed.
Should work fine with #25.

**Comment by thorade** [comment]
Thanks, installation now works, I'll report how the rest works once the zmq flag is in the nigthly build!

**Comment by thorade** [comment]
omc --version reports `OpenModelica 1.12.0~dev-818-g5c075f7`
Should that support ZMQ already or is ZMQ not yet in th enightlies?

I get the error message 
```
*** Error in `/usr/bin/omc': free(): invalid next size (normal): 0x00000000024ab7d0 ***
2017-06-16 08:25:32,064 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Aborted (core dumped)
```

https://travis-ci.org/thorade/ExtraMath/builds/243579105

**Comment by adeas31** [comment]
@thorade there was a problem initializing zmq on linux. I have already pushed in a fix https://github.com/OpenModelica/OMCompiler/pull/1686

ZMQ is already in the nightlies. However, you have to wait until tomorrow to get the fixes.

**Pull request merged**
