### PR TITLE
check for omc process status to avoid freezing

### PR DESCRIPTION
**Pull request by arun3688**

### CODE REVIEW

**Comment by JKRT** [comment]
@arun3688 Is this related to the issue I discussed with you and @lochel yesterday?

**Comment by arun3688** [comment]
@JKRT , Yes this should fix that issue, ZMQ poller also needs some kind of time out parameter, and i think this should be a more cleaner solution checking for the omc process status

**Comment by JKRT** [comment]
@arun3688 It was an issue here as well then, we should check the same thing in OMJulia and OMatlab I guess

**Comment by arun3688** [comment]
@JKRT Yes i also found the solution for OMJulia and OMMatlab also i will update it sooner

**Pull request merged**
